/**
 * Filename		: GPIO_HwAccess.h
 * Author		: Nghia Taarabt
 * Create Date 	: 18/12/22
 * Brief		: GPIO Hardware Access Specific for each Platform
 */

#ifndef __GPIO_HWACCESS_H__
#define __GPIO_HWACESS_H__

#include "GPIO_Base.h"
#include "GPIO_Types.h"
#include "RCC.h"

/**
 * GPIO ALternate Functions for STM32F401
 */
typedef enum 
{
	GPIO_ALTERNATE_SYSTEM				= GPIO_ALTERNATE_0,
	GPIO_ALTERNATE_TIMER1_2				= GPIO_ALTERNATE_1,
	GPIO_ALTERNATE_TIMER3_5				= GPIO_ALTERNATE_2,
	GPIO_ALTERNATE_TIMER9_11			= GPIO_ALTERNATE_3,
	GPIO_ALTERNATE_I2C1_3				= GPIO_ALTERNATE_4,
	GPIO_ALTERNATE_SPI1_4				= GPIO_ALTERNATE_5,
	GPIO_ALTERNATE_SPI3					= GPIO_ALTERNATE_6,
	GPIO_ALTERNATE_USART1_2				= GPIO_ALTERNATE_7,
	GPIO_ALTERNATE_USART_6				= GPIO_ALTERNATE_8,
	GPIO_ALTERNATE_I2C2_3				= GPIO_ALTERNATE_9,
	GPIO_ALTERNATE_OTG_FS				= GPIO_ALTERNATE_10,
	GPIO_ALTERNATE_REVERSED1			= GPIO_ALTERNATE_11,
	GPIO_ALTERNATE_SDIO					= GPIO_ALTERNATE_12,
	GPIO_ALTERNATE_REVERSED2			= GPIO_ALTERNATE_13,
	GPIO_ALTERNATE_REVERSED3			= GPIO_ALTERNATE_14,
	GPIO_ALTERNATE_EVENTOUT				= GPIO_ALTERNATE_15
} GPIO_AFSpecTypes;


#endif	/* __GPIO_HWACESS_H__ */
