################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.c \
D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.c 

OBJS += \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.o \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.o 

C_DEPS += \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.d \
./Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.d 


# Each subdirectory must supply rules for building sources it contributes
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_abs_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_add_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_dot_prod_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_mult_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_negate_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_offset_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_scale_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_shift_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.o: D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4\ Standard\ Peripheral\ Library/Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.c Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DARM_MATH_CM4 -DSTM32F4XX -DSTM32 -DSTM32F401RETx -DSTM32F4 -c -I../Inc -I"D:/STM32/STM32_SourceCode/Register Programming/Common_Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Include" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/STM32F4xx_StdPeriph_Driver/inc" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/ARM" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/G++" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Lib/GCC" -I"D:/STM32/STM32_SourceCode/STM32F4/STM32F4/STM32F4 Standard Peripheral Library/Libraries/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -v -fstack-usage -MMD -MP -MF"Libraries/CMSIS/DSP_Lib/Source/BasicMathFunctions/arm_sub_q7.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

