/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "USART.h"
#include "GPIO.h"
#include "Systick.h"

/* USART1 TX Pin */
#define USART1_TX_PIN					GPIO_PIN_NO_9
#define USART1_TX_PORT_INS				GPIO_INSTANCE_A

/* USART1 RX Pin */
#define USART1_RX_PIN					GPIO_PIN_NO_10
#define USART1_RX_PORT_INS				GPIO_INSTANCE_A

const uint8 TxBuff[] = "EFGHI";
uint8 RxBuff[5];

Usart_StateRuntimeType StateStruct;

const Usart_UserConfigType User_UART1_Config = {
		.USART_Mode				= USART_MODE_TXRX,
		.USART_Baud				= USART_STD_BAUD_9600,
		.USART_NoOfStopBits		= USART_STOPBITS_1,
		.USART_WordLength		= USART_WORDLEN_8BITS,
		.USART_ParityControl 	= USART_PARITY_DISABLE,
		.USART_HWFlowControl	= USART_HW_FLOW_CTRL_NONE,
		.StateStruct			= &StateStruct,
};

const  GPIO_PinConfigType User_UART1_TX_PinConfig = {
		USART1_TX_PIN,
		GPIO_MODE_ALTERNATE,
		GPIO_OSPEED_HIGH,
		GPIO_INPUT_PULLUP,
		GPIO_OTYPE_PUSHPULL,
		GPIO_ALTERNATE_USART1_2,
		EXTI_DISABLE
};


const  GPIO_PinConfigType User_UART1_RX_PinConfig = {
		USART1_RX_PIN,
		GPIO_MODE_ALTERNATE,
		GPIO_OSPEED_HIGH,
		GPIO_INPUT_PULLUP,
		GPIO_OTYPE_PUSHPULL,
		GPIO_ALTERNATE_USART1_2,
		EXTI_DISABLE
};

const GPIO_PinConfigType User_LedConfig = {
		GPIO_PIN_NO_5,
		GPIO_MODE_OUTPUT,
		GPIO_OSPEED_HIGH,
		GPIO_INPUT_FLOATING,
		GPIO_OTYPE_PUSHPULL,
		GPIO_ALTERNATE_REVERSED1,
		EXTI_DISABLE
};

void Delay(uint32 utime)
{
	while (utime--)
	{
		for (uint32 i = 0; i < 1000; i++);
	}
}

volatile Usart_StatusType CheckStatus;

void USART_TC_001(void)
{
	GPIO_Init(USART1_RX_PORT_INS, &User_UART1_RX_PinConfig);
	GPIO_Init(USART1_TX_PORT_INS, &User_UART1_TX_PinConfig);
	// GPIO_Init(GPIO_ALT_UART_1_RX_INS, &User_UART1_RX_PinConfig);
	Systick_Init(1000000U);

	USART_Init(UART_INSTANCE_1, &User_UART1_Config);

	CheckStatus = Usart_SyncReceiveData(UART_INSTANCE_1, RxBuff, 5, 10000000);

	if (CheckStatus == USART_STATUS_SUCCESS)
	{
		CheckStatus = Usart_SyncSendData(UART_INSTANCE_1, TxBuff, 6, 10000000);
	}

	/* Loop forever */
	for(;;)
	{
		GPIO_ToggleOutputPin(GPIO_INSTANCE_A, GPIO_PIN_NO_5);
		Delay(500);
	}
}
